# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcomeSettings_v2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(643, 406)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.welcome = QtWidgets.QWidget()
        self.welcome.setObjectName("welcome")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.welcome)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_container1 = QtWidgets.QFrame(self.welcome)
        self.frame_container1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_container1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_container1.setObjectName("frame_container1")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_container1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame_text1 = QtWidgets.QFrame(self.frame_container1)
        self.frame_text1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_text1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_text1.setObjectName("frame_text1")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_text1)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_6 = QtWidgets.QLabel(self.frame_text1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setScaledContents(False)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.gridLayout_12.addWidget(self.label_6, 1, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.frame_text1)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName("label_7")
        self.gridLayout_12.addWidget(self.label_7, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem, 2, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_text1, 0, 0, 1, 1)
        self.frame_buttons1 = QtWidgets.QFrame(self.frame_container1)
        self.frame_buttons1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons1.setObjectName("frame_buttons1")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_buttons1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.next_page2 = QtWidgets.QPushButton(self.frame_buttons1)
        self.next_page2.setObjectName("next_page2")
        self.gridLayout_8.addWidget(self.next_page2, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_buttons1, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_container1, 4, 0, 1, 1)
        self.stackedWidget.addWidget(self.welcome)
        self.platform = QtWidgets.QWidget()
        self.platform.setObjectName("platform")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.platform)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_container2 = QtWidgets.QFrame(self.platform)
        self.frame_container2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_container2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_container2.setObjectName("frame_container2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_container2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_text2 = QtWidgets.QFrame(self.frame_container2)
        self.frame_text2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_text2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_text2.setObjectName("frame_text2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_text2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_text2)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_text2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_text2, 2, 0, 1, 1)
        self.frame_buttons2 = QtWidgets.QFrame(self.frame_container2)
        self.frame_buttons2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons2.setObjectName("frame_buttons2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_buttons2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.prev_page1 = QtWidgets.QPushButton(self.frame_buttons2)
        self.prev_page1.setObjectName("prev_page1")
        self.gridLayout_7.addWidget(self.prev_page1, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(402, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 0, 1, 1, 1)
        self.next_page3 = QtWidgets.QPushButton(self.frame_buttons2)
        self.next_page3.setObjectName("next_page3")
        self.gridLayout_7.addWidget(self.next_page3, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.frame_buttons2, 3, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_container2, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.platform)
        self.store_name = QtWidgets.QWidget()
        self.store_name.setObjectName("store_name")
        self.gridLayout = QtWidgets.QGridLayout(self.store_name)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.store_name)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.frame_text2_3 = QtWidgets.QFrame(self.frame)
        self.frame_text2_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_text2_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_text2_3.setObjectName("frame_text2_3")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_text2_3)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_8 = QtWidgets.QLabel(self.frame_text2_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_15.addWidget(self.label_8, 1, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.frame_text2_3)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_9.setObjectName("label_9")
        self.gridLayout_15.addWidget(self.label_9, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem4, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem5, 4, 0, 1, 1)
        self.store_names = QtWidgets.QLineEdit(self.frame_text2_3)
        self.store_names.setObjectName("store_names")
        self.gridLayout_15.addWidget(self.store_names, 3, 0, 1, 2)
        self.gridLayout_16.addWidget(self.frame_text2_3, 0, 0, 1, 1)
        self.frame_buttons2_3 = QtWidgets.QFrame(self.frame)
        self.frame_buttons2_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons2_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons2_3.setObjectName("frame_buttons2_3")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_buttons2_3)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem6, 1, 1, 1, 1)
        self.next_page4 = QtWidgets.QPushButton(self.frame_buttons2_3)
        self.next_page4.setObjectName("next_page4")
        self.gridLayout_14.addWidget(self.next_page4, 1, 2, 1, 1)
        self.prev_page2 = QtWidgets.QPushButton(self.frame_buttons2_3)
        self.prev_page2.setObjectName("prev_page2")
        self.gridLayout_14.addWidget(self.prev_page2, 1, 0, 1, 1)
        self.gridLayout_16.addWidget(self.frame_buttons2_3, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.store_name)
        self.main_category = QtWidgets.QWidget()
        self.main_category.setObjectName("main_category")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.main_category)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.frame_2 = QtWidgets.QFrame(self.main_category)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.frame_text2_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_text2_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_text2_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_text2_4.setObjectName("frame_text2_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_text2_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_11 = QtWidgets.QLabel(self.frame_text2_4)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_text2_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(558, 67, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem7, 2, 0, 1, 1)
        self.store_main_category = QtWidgets.QLineEdit(self.frame_text2_4)
        self.store_main_category.setObjectName("store_main_category")
        self.gridLayout_9.addWidget(self.store_main_category, 3, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(558, 67, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem8, 4, 0, 1, 1)
        self.gridLayout_20.addWidget(self.frame_text2_4, 0, 0, 1, 1)
        self.frame_buttons2_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_buttons2_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons2_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons2_4.setObjectName("frame_buttons2_4")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frame_buttons2_4)
        self.gridLayout_19.setObjectName("gridLayout_19")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem9, 1, 1, 1, 1)
        self.next_page5 = QtWidgets.QPushButton(self.frame_buttons2_4)
        self.next_page5.setObjectName("next_page5")
        self.gridLayout_19.addWidget(self.next_page5, 1, 2, 1, 1)
        self.prev_page3 = QtWidgets.QPushButton(self.frame_buttons2_4)
        self.prev_page3.setObjectName("prev_page3")
        self.gridLayout_19.addWidget(self.prev_page3, 1, 0, 1, 1)
        self.gridLayout_20.addWidget(self.frame_buttons2_4, 1, 0, 1, 1)
        self.gridLayout_17.addWidget(self.frame_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.main_category)
        self.sub_categories = QtWidgets.QWidget()
        self.sub_categories.setObjectName("sub_categories")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.sub_categories)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.frame_3 = QtWidgets.QFrame(self.sub_categories)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.frame_text2_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_text2_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_text2_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_text2_5.setObjectName("frame_text2_5")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.frame_text2_5)
        self.gridLayout_22.setObjectName("gridLayout_22")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_22.addItem(spacerItem10, 4, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_22.addItem(spacerItem11, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_text2_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.gridLayout_22.addWidget(self.label_12, 1, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.frame_text2_5)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_13.setObjectName("label_13")
        self.gridLayout_22.addWidget(self.label_13, 0, 0, 1, 1)
        self.store_sub_categories = QtWidgets.QLineEdit(self.frame_text2_5)
        self.store_sub_categories.setObjectName("store_sub_categories")
        self.gridLayout_22.addWidget(self.store_sub_categories, 3, 0, 1, 2)
        self.gridLayout_24.addWidget(self.frame_text2_5, 0, 0, 1, 1)
        self.frame_buttons2_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_buttons2_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons2_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons2_5.setObjectName("frame_buttons2_5")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.frame_buttons2_5)
        self.gridLayout_23.setObjectName("gridLayout_23")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem12, 1, 1, 1, 1)
        self.next_page6 = QtWidgets.QPushButton(self.frame_buttons2_5)
        self.next_page6.setObjectName("next_page6")
        self.gridLayout_23.addWidget(self.next_page6, 1, 2, 1, 1)
        self.prev_page4 = QtWidgets.QPushButton(self.frame_buttons2_5)
        self.prev_page4.setObjectName("prev_page4")
        self.gridLayout_23.addWidget(self.prev_page4, 1, 0, 1, 1)
        self.gridLayout_24.addWidget(self.frame_buttons2_5, 1, 0, 1, 1)
        self.gridLayout_21.addWidget(self.frame_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.sub_categories)
        self.dataset = QtWidgets.QWidget()
        self.dataset.setObjectName("dataset")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.dataset)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.frame_4 = QtWidgets.QFrame(self.dataset)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.frame_text2_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_text2_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_text2_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_text2_6.setObjectName("frame_text2_6")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.frame_text2_6)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.label_14 = QtWidgets.QLabel(self.frame_text2_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.gridLayout_26.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_text2_6)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_15.setObjectName("label_15")
        self.gridLayout_26.addWidget(self.label_15, 0, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_26.addItem(spacerItem13, 2, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_26.addItem(spacerItem14, 4, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_text2_6)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.path_str = QtWidgets.QLabel(self.frame_5)
        self.path_str.setObjectName("path_str")
        self.horizontalLayout.addWidget(self.path_str)
        self.dataset_path = QtWidgets.QToolButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataset_path.sizePolicy().hasHeightForWidth())
        self.dataset_path.setSizePolicy(sizePolicy)
        self.dataset_path.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dataset_path.setObjectName("dataset_path")
        self.horizontalLayout.addWidget(self.dataset_path)
        self.gridLayout_10.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_26.addWidget(self.frame_5, 3, 0, 1, 1)
        self.gridLayout_28.addWidget(self.frame_text2_6, 0, 0, 1, 1)
        self.frame_buttons2_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_buttons2_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons2_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons2_6.setObjectName("frame_buttons2_6")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.frame_buttons2_6)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.prev_page5 = QtWidgets.QPushButton(self.frame_buttons2_6)
        self.prev_page5.setObjectName("prev_page5")
        self.gridLayout_27.addWidget(self.prev_page5, 0, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem15, 0, 1, 1, 1)
        self.finish_settings = QtWidgets.QPushButton(self.frame_buttons2_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.finish_settings.setFont(font)
        self.finish_settings.setObjectName("finish_settings")
        self.gridLayout_27.addWidget(self.finish_settings, 0, 2, 1, 1)
        self.gridLayout_28.addWidget(self.frame_buttons2_6, 1, 0, 1, 1)
        self.gridLayout_29.addWidget(self.frame_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.dataset)
        self.gridLayout_4.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "\n"
"Before we start, lets set some initial settings.\n"
"We will guide you step by step.\n"
"\n"
"click Next when you ready to start."))
        self.label_7.setText(_translate("MainWindow", "Welcome"))
        self.next_page2.setText(_translate("MainWindow", "Next"))
        self.label_2.setText(_translate("MainWindow", "Platform"))
        self.label_4.setText(_translate("MainWindow", "Curently this application is supporting only Etsy e-commernce website.\n"
"Later on when this project will be an open-source project,\n"
"more platforms can be added"))
        self.prev_page1.setText(_translate("MainWindow", "Previous"))
        self.next_page3.setText(_translate("MainWindow", "Next"))
        self.label_8.setText(_translate("MainWindow", "Please add your store\'s name in the platform.\n"
" If you have multiple stores, add them all.\n"
"Use comma ( , ) as separator"))
        self.label_9.setText(_translate("MainWindow", "Store Name"))
        self.store_names.setPlaceholderText(_translate("MainWindow", "Stores separated by comma"))
        self.next_page4.setText(_translate("MainWindow", "Next"))
        self.prev_page2.setText(_translate("MainWindow", "Previous"))
        self.label_11.setText(_translate("MainWindow", "Main Category"))
        self.label_10.setText(_translate("MainWindow", "\n"
"Please specify the main category of your store"))
        self.store_main_category.setPlaceholderText(_translate("MainWindow", "Store\'s main category"))
        self.next_page5.setText(_translate("MainWindow", "Next"))
        self.prev_page3.setText(_translate("MainWindow", "Previous"))
        self.label_12.setText(_translate("MainWindow", "Sometimes items in your store have sub categories,\n"
"Please include all your item\'s sub categories.\n"
"Use comma ( , ) as a seperator"))
        self.label_13.setText(_translate("MainWindow", "Sub Categories"))
        self.store_sub_categories.setPlaceholderText(_translate("MainWindow", "All item\'s sub categories separated by comma"))
        self.next_page6.setText(_translate("MainWindow", "Next"))
        self.prev_page4.setText(_translate("MainWindow", "Previous"))
        self.label_14.setText(_translate("MainWindow", "Please specify an initial directory which contains all your pictures you wish us to compare.\n"
"Those pictures will be checked if somebody used them else where in the platform"))
        self.label_15.setText(_translate("MainWindow", "Path To Your Files"))
        self.path_str.setText(_translate("MainWindow", "Please choose your intial directory"))
        self.dataset_path.setText(_translate("MainWindow", "Browse"))
        self.prev_page5.setText(_translate("MainWindow", "Previous"))
        self.finish_settings.setText(_translate("MainWindow", "FINISH"))
