<RuntimeScreen>:
    FloatLayout:
        Label:
            pos_hint: {'x':0, 'y': 0.25}
            font_size: 15
            id: run_status
            text: "Searching ETSY platform for stores and downloading their products."
        Button:
            pos_hint: {'center_x':0.5, 'y': 0.25}
            size_hint_y: None
            height: self.texture_size[1]
            width: 200
            font_size: 40

            text: "Stop"
            on_release: root.manager.switch_to_menu()