# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(757, 562)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("border:0")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_19.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_19.addWidget(self.label_2, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.home_tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setKerning(True)
        self.home_tab.setFont(font)
        self.home_tab.setStyleSheet("")
        self.home_tab.setObjectName("home_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.home_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.home_tab)
        self.stackedWidget.setObjectName("stackedWidget")
        self.before_run = QtWidgets.QWidget()
        self.before_run.setObjectName("before_run")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.before_run)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.before_run)
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.start_btn = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_btn.sizePolicy().hasHeightForWidth())
        self.start_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(True)
        self.start_btn.setFont(font)
        self.start_btn.setStyleSheet("QPushButton#start_btn {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 30px;\n"
"    border: 2px solid gray;\n"
"    padding: 0 8px;\n"
"    background: #7FFF00;\n"
"    min-width: 10em;\n"
"    min-height: 3em;\n"
"}\n"
"\n"
"QPushButton#start_btn:pressed {\n"
"    background-color:#6B8E23;\n"
"    border-style: inset;\n"
"}")
        self.start_btn.setObjectName("start_btn")
        self.gridLayout.addWidget(self.start_btn, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.frame_5, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.before_run)
        self.frame_2.setStyleSheet("border:0")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("border:0")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.gridLayout_4.addWidget(self.frame_3, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("border:0")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_4)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_5.addWidget(self.comboBox, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_4, 1, 2, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.before_run)
        self.runtime = QtWidgets.QWidget()
        self.runtime.setObjectName("runtime")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.runtime)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_6 = QtWidgets.QFrame(self.runtime)
        self.frame_6.setStyleSheet("border:0")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setStyleSheet("border:0")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setStyleSheet("border:0")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        self.frame_10.setStyleSheet("border:0")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 0, 1, 1, 1)
        self.method_label = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.method_label.setFont(font)
        self.method_label.setObjectName("method_label")
        self.gridLayout_8.addWidget(self.method_label, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_10)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setStyleSheet("border:0")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setStyleSheet("border:0")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.status_label = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.status_label.setFont(font)
        self.status_label.setObjectName("status_label")
        self.gridLayout_10.addWidget(self.status_label, 2, 2, 1, 1)
        self.task_label = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.task_label.setFont(font)
        self.task_label.setObjectName("task_label")
        self.gridLayout_10.addWidget(self.task_label, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_10.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem5, 2, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem6, 0, 3, 1, 1)
        self.gridLayout_9.addWidget(self.frame_11, 0, 0, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setStyleSheet("border:0")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.progressBar = QtWidgets.QProgressBar(self.frame_12)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_11.addWidget(self.progressBar, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_12, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.gridLayout_6.addWidget(self.frame_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.runtime)
        self.multi_run = QtWidgets.QWidget()
        self.multi_run.setObjectName("multi_run")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.multi_run)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frame_14 = QtWidgets.QFrame(self.multi_run)
        self.frame_14.setStyleSheet("border:0")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_7 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_17.addWidget(self.label_7, 0, 0, 1, 1)
        self.pd_task_label = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pd_task_label.setFont(font)
        self.pd_task_label.setObjectName("pd_task_label")
        self.gridLayout_17.addWidget(self.pd_task_label, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem7, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_17.addWidget(self.label_9, 1, 0, 1, 1)
        self.pd_status_label = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pd_status_label.setFont(font)
        self.pd_status_label.setObjectName("pd_status_label")
        self.gridLayout_17.addWidget(self.pd_status_label, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem8, 1, 2, 1, 1)
        self.gridLayout_12.addWidget(self.frame_14, 1, 0, 1, 1)
        self.frame_20 = QtWidgets.QFrame(self.multi_run)
        self.frame_20.setStyleSheet("border:0")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.im_progressBar_2 = QtWidgets.QProgressBar(self.frame_20)
        self.im_progressBar_2.setProperty("value", 24)
        self.im_progressBar_2.setObjectName("im_progressBar_2")
        self.gridLayout_20.addWidget(self.im_progressBar_2, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frame_20, 2, 0, 1, 1)
        self.frame_13 = QtWidgets.QFrame(self.multi_run)
        self.frame_13.setStyleSheet("border:0")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        self.frame_15.setStyleSheet("border:0")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.im_progressBar = QtWidgets.QProgressBar(self.frame_15)
        self.im_progressBar.setProperty("value", 24)
        self.im_progressBar.setObjectName("im_progressBar")
        self.gridLayout_14.addWidget(self.im_progressBar, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_15, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frame_13, 5, 0, 1, 1)
        self.frame_16 = QtWidgets.QFrame(self.multi_run)
        self.frame_16.setStyleSheet("border:0")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        self.frame_17.setStyleSheet("border:0")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_10 = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_15.addWidget(self.label_10, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_16)
        self.frame_18.setStyleSheet("border:0")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_16.setObjectName("gridLayout_16")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem9, 0, 1, 1, 1)
        self.method_label_2 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.method_label_2.setFont(font)
        self.method_label_2.setObjectName("method_label_2")
        self.gridLayout_16.addWidget(self.method_label_2, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_18)
        self.gridLayout_12.addWidget(self.frame_16, 0, 0, 1, 1)
        self.frame_19 = QtWidgets.QFrame(self.multi_run)
        self.frame_19.setStyleSheet("border:0")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_19)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_11 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_18.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_18.addWidget(self.label_12, 1, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem10, 1, 2, 1, 1)
        self.im_status_label = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.im_status_label.setFont(font)
        self.im_status_label.setObjectName("im_status_label")
        self.gridLayout_18.addWidget(self.im_status_label, 1, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem11, 0, 2, 1, 1)
        self.im_task_label = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.im_task_label.setFont(font)
        self.im_task_label.setObjectName("im_task_label")
        self.gridLayout_18.addWidget(self.im_task_label, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.frame_19, 4, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem12, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.multi_run)
        self.summary = QtWidgets.QWidget()
        self.summary.setObjectName("summary")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.summary)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.results_layout = QtWidgets.QVBoxLayout()
        self.results_layout.setObjectName("results_layout")
        self.results_lbl = QtWidgets.QLabel(self.summary)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.results_lbl.setFont(font)
        self.results_lbl.setObjectName("results_lbl")
        self.results_layout.addWidget(self.results_lbl)
        self.gridLayout_21.addLayout(self.results_layout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.summary)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.home_tab, "")
        self.hitory_tab = QtWidgets.QWidget()
        self.hitory_tab.setObjectName("hitory_tab")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.hitory_tab)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.results_layout_2 = QtWidgets.QVBoxLayout()
        self.results_layout_2.setObjectName("results_layout_2")
        self.results_lbl_2 = QtWidgets.QLabel(self.hitory_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.results_lbl_2.setFont(font)
        self.results_lbl_2.setObjectName("results_lbl_2")
        self.results_layout_2.addWidget(self.results_lbl_2)
        self.frame_21 = QtWidgets.QFrame(self.hitory_tab)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout.setObjectName("verticalLayout")
        self.results_layout_2.addWidget(self.frame_21)
        self.gridLayout_22.addLayout(self.results_layout_2, 1, 0, 1, 1)
        self.frame_22 = QtWidgets.QFrame(self.hitory_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_22.sizePolicy().hasHeightForWidth())
        self.frame_22.setSizePolicy(sizePolicy)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.export_history_btn = QtWidgets.QPushButton(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_history_btn.sizePolicy().hasHeightForWidth())
        self.export_history_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.export_history_btn.setFont(font)
        self.export_history_btn.setAutoExclusive(False)
        self.export_history_btn.setObjectName("export_history_btn")
        self.horizontalLayout_3.addWidget(self.export_history_btn)
        self.gridLayout_22.addWidget(self.frame_22, 2, 0, 1, 1)
        self.tabWidget.addTab(self.hitory_tab, "")
        self.gridLayout_19.addWidget(self.tabWidget, 2, 0, 1, 1)
        self.gridLayout_23.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 757, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_us = QtWidgets.QAction(MainWindow)
        self.actionAbout_us.setObjectName("actionAbout_us")
        self.menuAbout.addAction(self.actionAbout_us)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "MIPAS"))
        self.label_2.setText(_translate("MainWindow", "Merchant\'s Intellectual Property Authentication System"))
        self.start_btn.setText(_translate("MainWindow", "START"))
        self.label_3.setText(_translate("MainWindow", "Shop Searching Method"))
        self.label_4.setText(_translate("MainWindow", "Choose an option how to perform the next shop search\n"
"after chosen method -\n"
"found products will be compared to given dataset"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Start New Search"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Search Found Stores From Previous Run"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Compare Only With What I Got"))
        self.label_5.setText(_translate("MainWindow", "Chosen Shop Searching Method:"))
        self.method_label.setText(_translate("MainWindow", "... method chosen by user ..."))
        self.status_label.setText(_translate("MainWindow", "... current status ..."))
        self.task_label.setText(_translate("MainWindow", "... current task ..."))
        self.label_6.setText(_translate("MainWindow", "Current Task:"))
        self.label_8.setText(_translate("MainWindow", "Status:"))
        self.label_7.setText(_translate("MainWindow", "Products Download - Current Task:"))
        self.pd_task_label.setText(_translate("MainWindow", "... current task ..."))
        self.label_9.setText(_translate("MainWindow", "Products Download - Status:"))
        self.pd_status_label.setText(_translate("MainWindow", "... current status ..."))
        self.label_10.setText(_translate("MainWindow", "Chosen Shop Searching Method:"))
        self.method_label_2.setText(_translate("MainWindow", "... method chosen by user ..."))
        self.label_11.setText(_translate("MainWindow", "Image Matching - Current Task:"))
        self.label_12.setText(_translate("MainWindow", "Image Matching - Status:"))
        self.im_status_label.setText(_translate("MainWindow", "... current status ..."))
        self.im_task_label.setText(_translate("MainWindow", "... current task ..."))
        self.results_lbl.setText(_translate("MainWindow", "Results:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.home_tab), _translate("MainWindow", "Home"))
        self.results_lbl_2.setText(_translate("MainWindow", "Results:"))
        self.export_history_btn.setText(_translate("MainWindow", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.hitory_tab), _translate("MainWindow", "History"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionAbout_us.setText(_translate("MainWindow", "About us"))

